issuesOpened: >
  If this is a question about Moonlight or you need help troubleshooting a streaming problem, please use the help channels on our [Discord server](https://moonlight-stream.org/discord) instead of GitHub issues. There are many more people available on Discord to help you and answer your questions.<br /><br />
  This issue tracker should only be used for specific bugs or feature requests.<br /><br />
  Thank you, and happy streaming!
