name: Feature Request
description: Suggest a new feature or improvement
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the feature you would like to see added to Moonlight.
      placeholder: "Example: I would like to see support for a feature like X."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why do you think this feature should be added?
      placeholder: "Example: It would provide a better streaming experience."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Example: This feature exists in other Moonlight clients."
